# Spécifie l'image de base à utiliser, qui est "node:alpine"
FROM node:alpine

# Définit le répertoire de travail pour l'application dans le conteneur
WORKDIR /home/app

# La construction de l'image Docker est terminée